In [27]:
import sys
import numpy as np
import pandas as pd
import csv

# Data Describe

In [28]:
df = pd.read_csv('train.csv', encoding = 'big5')   # 4321* 27
df.head(18)

日期  測站          測項     0     1     2     3     4     5     6  ...  \
0   2014/1/1  豐原    AMB_TEMP    14    14    14    13    12    12    12  ...   
1   2014/1/1  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...   
2   2014/1/1  豐原          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37  ...   
3   2014/1/1  豐原        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1  ...   
4   2014/1/1  豐原          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9  ...   
5   2014/1/1  豐原         NO2    16   9.2   8.2   6.9   6.8   3.8   6.9  ...   
6   2014/1/1  豐原         NOx    17   9.8   8.7   8.6   8.5   5.3   8.8  ...   
7   2014/1/1  豐原          O3    16    30    27    23    24    28    24  ...   
8   2014/1/1  豐原        PM10    56    50    48    35    25    12     4  ...   
9   2014/1/1  豐原       PM2.5    26    39    36    35    31    28    25  ...   
10  2014/1/1  豐原    RAINFALL    NR    NR    NR    NR    NR    NR    NR  ...   
11  2014/1/1  豐原          RH    77    68    67    74    72    73    74  ...   
12  2014/1/1  豐原         SO2   1.8     2   1.7   1.6   1.9   1.4   1.5  ...   
13  2014/1/1  豐原         THC     2     2     2   1.9   1.9   1.8   1.9  ...   
14  2014/1/1  豐原       WD_HR    37    80    57    76   110   106   101  ...   
15  2014/1/1  豐原  WIND_DIREC    35    79   2.4    55    94   116   106  ...   
16  2014/1/1  豐原  WIND_SPEED   1.4   1.8     1   0.6   1.7   2.5   2.5  ...   
17  2014/1/1  豐原       WS_HR   0.5   0.9   0.6   0.3   0.6   1.9     2  ...   

      14    15    16    17    18    19    20    21    22    23  
0     22    22    21    19    17    16    15    15    15    15  
1    1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2   0.37  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3    0.1  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  
4    2.5   2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8   1.5  
5     11    11    22    28    19    12   8.1     7   6.9     6  
6     14    13    25    30    21    13   9.7   8.6   8.7   7.5  
7     65    64    51    34    33    34    37    38    38    36  
8     52    51    66    85    85    63    46    36    42    42  
9     36    45    42    49    45    44    41    30    24    13  
10    NR    NR    NR    NR    NR    NR    NR    NR    NR    NR  
11    47    49    56    67    72    69    70    70    70    69  
12   3.9   4.4   9.9   5.1   3.4   2.3     2   1.9   1.9   1.9  
13   1.9   1.9   1.9   2.1     2   1.9   1.9   1.9   1.9   1.9  
14   307   304   307   124   118   121   113   112   106   110  
15   313   305   291   124   119   118   114   108   102   111  
16   2.5   2.2   1.4   2.2   2.8     3   2.6   2.7   2.1   2.1  
17   2.1   2.1   1.9     1   2.5   2.5   2.8   2.6   2.4   2.3  

[18 rows x 27 columns]

In [29]:
df = pd.read_csv('test.csv', encoding = 'big5')   
df.head(17)

id_0    AMB_TEMP    21  21.1    20  20.1    19  19.1  19.2    18    17
0   id_0         CH4   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.8
1   id_0          CO  0.39  0.36  0.36   0.4  0.53  0.55  0.34  0.31  0.23
2   id_0        NMHC  0.16  0.24  0.22  0.27  0.27  0.26  0.27  0.29   0.1
3   id_0          NO   1.3   1.3   1.3   1.3   1.4   1.6   1.2   1.1   0.9
4   id_0         NO2    17    14    13    14    18    21   8.9   9.4     5
5   id_0         NOx    18    16    14    15    20    23    10    10   5.8
6   id_0          O3    32    31    31    26    16    12    27    20    26
7   id_0        PM10    62    50    44    39    38    32    48    36    25
8   id_0       PM2.5    33    39    39    25    18    18    17     9     4
9   id_0    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
10  id_0          RH    83    85    87    87    86    85    78    81    80
11  id_0         SO2     2   1.8   1.8   1.8   2.1   2.6     2   2.3   2.4
12  id_0         THC   1.8   1.9   1.9     2     2     2     2     2   1.9
13  id_0       WD_HR    58    53    67    59    59    73    79    82   104
14  id_0  WIND_DIREC    57    44    73    44    56   115    45   107   103
15  id_0  WIND_SPEED   1.4   1.3   1.5   1.4   1.6   1.6   1.2   1.8   2.3
16  id_0       WS_HR     1   0.9   0.9   0.9   1.2   0.7     1   0.6   1.8

In [30]:
raw_data = np.genfromtxt('train.csv', delimiter=',', encoding = 'big5')
data = raw_data[1:,3:]   # 4320 * 24   , 24hr , 4320= 18-dim * 12months * 20days
where_are_NaNs = np.isnan(data)
data[where_are_NaNs] = 0 
month_to_data = {}  ## Dictionary (key:month , value:data)                                  
for month in range(12):
    sample = np.empty(shape = (18 , 480)) # sample : every month data :18-dim * 480hrs (20days * 24hr)
    for day in range(20):
        for hour in range(24): 
            sample[:,day * 24 + hour] = data[18 * (month * 20 + day): 18 * (month * 20 + day + 1),hour]
    month_to_data[month] = sample    # month_to_data : 12 months * 18-dim * 480 

In [31]:
x = np.empty(shape = (12 * 471 , 18 * 9),dtype = float) # the prvious 9 hour as model input ,ans concate,so 18*9
y = np.empty(shape = (12 * 471 , 1),dtype = float)  # the 10th hour as model target

for month in range(12): 
    for day in range(20): 
        for hour in range(24):   
            if day == 19 and hour > 14:
                continue  
            x[month * 471 + day * 24 + hour,:] = month_to_data[month][:,day * 24 + hour : day * 24 + hour + 9].reshape(1,-1) 
            #  * 18-dim * 9 
            y[month * 471 + day * 24 + hour,0] = month_to_data[month][9 ,day * 24 + hour + 9]

In [32]:
month_to_data[0][:,0 * 24 + 0 : 0 * 24 + 0 + 9].reshape(1,-1)

array([[1.40e+01, 1.40e+01, 1.40e+01, 1.30e+01, 1.20e+01, 1.20e+01,
        1.20e+01, 1.20e+01, 1.50e+01, 1.80e+00, 1.80e+00, 1.80e+00,
        1.80e+00, 1.80e+00, 1.80e+00, 1.80e+00, 1.80e+00, 1.80e+00,
        5.10e-01, 4.10e-01, 3.90e-01, 3.70e-01, 3.50e-01, 3.00e-01,
        3.70e-01, 4.70e-01, 7.80e-01, 2.00e-01, 1.50e-01, 1.30e-01,
        1.20e-01, 1.10e-01, 6.00e-02, 1.00e-01, 1.30e-01, 2.60e-01,
        9.00e-01, 6.00e-01, 5.00e-01, 1.70e+00, 1.80e+00, 1.50e+00,
        1.90e+00, 2.20e+00, 6.60e+00, 1.60e+01, 9.20e+00, 8.20e+00,
        6.90e+00, 6.80e+00, 3.80e+00, 6.90e+00, 7.80e+00, 1.50e+01,
        1.70e+01, 9.80e+00, 8.70e+00, 8.60e+00, 8.50e+00, 5.30e+00,
        8.80e+00, 9.90e+00, 2.20e+01, 1.60e+01, 3.00e+01, 2.70e+01,
        2.30e+01, 2.40e+01, 2.80e+01, 2.40e+01, 2.20e+01, 2.10e+01,
        5.60e+01, 5.00e+01, 4.80e+01, 3.50e+01, 2.50e+01, 1.20e+01,
        4.00e+00, 2.00e+00, 1.10e+01, 2.60e+01, 3.90e+01, 3.60e+01,
        3.50e+01, 3.10e+01, 2.80e+01, 2.50e+01, 

# Normalization

In [33]:
x  # 1 * (12*471) * (18*9) 

array([[14. , 14. , 14. , ...,  2. ,  2. ,  0.5],
       [14. , 14. , 13. , ...,  2. ,  0.5,  0.3],
       [14. , 13. , 12. , ...,  0.5,  0.3,  0.8],
       ...,
       [17. , 18. , 19. , ...,  1.1,  1.4,  1.3],
       [18. , 19. , 18. , ...,  1.4,  1.3,  1.6],
       [19. , 18. , 17. , ...,  1.3,  1.6,  1.8]])

In [34]:
train_x = (x-np.mean(x,axis=0))/np.std(x,axis=0)
train_xx = x/np.max(x,axis =0)

#mean = np.mean(x, axis = 0) 
#std = np.std(x, axis = 0)
#for i in range(x.shape[0]):
 #   for j in range(x.shape[1]):
  #      if not std[j] == 0 :
   #         train_x[i][j] = (train_x[i][j]- mean[j]) / std[j]

In [35]:
train_x

array([[-1.35825331, -1.35883937, -1.359222  , ...,  0.26650729,
         0.2656797 , -1.14082131],
       [-1.35825331, -1.35883937, -1.51819928, ...,  0.26650729,
        -1.13963133, -1.32832904],
       [-1.35825331, -1.51789368, -1.67717656, ..., -1.13923451,
        -1.32700613, -0.85955971],
       ...,
       [-0.88092053, -0.72262212, -0.56433559, ..., -0.57693779,
        -0.29644471, -0.39079039],
       [-0.7218096 , -0.56356781, -0.72331287, ..., -0.29578943,
        -0.39013211, -0.1095288 ],
       [-0.56269867, -0.72262212, -0.88229015, ..., -0.38950555,
        -0.10906991,  0.07797893]])

In [36]:
train_xx

array([[0.38888889, 0.38888889, 0.38888889, ..., 0.28571429, 0.28571429,
        0.07142857],
       [0.38888889, 0.38888889, 0.36111111, ..., 0.28571429, 0.07142857,
        0.04285714],
       [0.38888889, 0.36111111, 0.33333333, ..., 0.07142857, 0.04285714,
        0.11428571],
       ...,
       [0.47222222, 0.5       , 0.52777778, ..., 0.15714286, 0.2       ,
        0.18571429],
       [0.5       , 0.52777778, 0.5       , ..., 0.2       , 0.18571429,
        0.22857143],
       [0.52777778, 0.5       , 0.47222222, ..., 0.18571429, 0.22857143,
        0.25714286]])

In [37]:
train_x

array([[-1.35825331, -1.35883937, -1.359222  , ...,  0.26650729,
         0.2656797 , -1.14082131],
       [-1.35825331, -1.35883937, -1.51819928, ...,  0.26650729,
        -1.13963133, -1.32832904],
       [-1.35825331, -1.51789368, -1.67717656, ..., -1.13923451,
        -1.32700613, -0.85955971],
       ...,
       [-0.88092053, -0.72262212, -0.56433559, ..., -0.57693779,
        -0.29644471, -0.39079039],
       [-0.7218096 , -0.56356781, -0.72331287, ..., -0.29578943,
        -0.39013211, -0.1095288 ],
       [-0.56269867, -0.72262212, -0.88229015, ..., -0.38950555,
        -0.10906991,  0.07797893]])

In [38]:
2**int(2/100)

1

# Training 

In [39]:
dim = x.shape[1] + 1 
#w = np.zeros(shape = (dim, 1 ))
#w = np.random.normal(loc =0 ,scale = 1,size = (dim,1))
w = np.random.normal(loc =0 ,scale = np.sqrt(1/train_x.shape[1]),size = (dim,1))
X = np.concatenate((np.ones((train_x.shape[0], 1 )), train_x) , axis = 1).astype(float)
# X: 1* 5652 * 163 ,y: 1 *5652*1
learning_rate = np.array([[200]] * dim)
#learning_rate = np.array( [ [[1]] * dim ,[[0.5]]* dim ,[[0.025]]*dim ]) 
adagrad_sum = np.zeros(shape = (dim, 1 ))
# shuffle 
shuffle = np.concatenate( (X,y) ,axis=1) 
np.random.shuffle( shuffle)
X = shuffle[:,:-1]
y = shuffle[:,-1].reshape(-1,1)

for T in range(10000): 
    learning_rate = np.array([[1* (0.5**int(T/1000))]] * dim )
    
    """
    if(T%100==0):
        # shuffle 
        shuffle = np.concatenate( (X,y) ,axis=1) 
        np.random.shuffle( shuffle)
        X = shuffle[:,:-1]
        y = shuffle[:,-1].reshape(-1,1)
    """


    if(T % 500 == 0 ):
        print("T=",T)
        print("Loss:",np.sum(np.power(X.dot(w) - y, 2 ))/ X.shape[0] )
    # no batch , taining all data     
    #gradient = (-2) * np.transpose(X).dot(y-X.dot(w))
    #adagrad_sum += gradient ** 2
    #w = w - learning_rate * gradient / (np.sqrt(adagrad_sum) + 0.0005)
    
    
    # batch
    for j in range(12):
        gradient = (-2) * np.transpose(X[471*j:471*(j+1)]).dot(y[471*j:471*(j+1)]-X[471*j:471*(j+1)].dot(w))
        adagrad_sum += gradient ** 2
        w = w - learning_rate * gradient / (np.sqrt(adagrad_sum) + 0.0005)
    
    
np.save('weight.npy',w)     ## save weight

T= 0
Loss: 726.4986568948024
T= 500
Loss: 32.420340824025466
T= 1000
Loss: 32.382144992980564
T= 1500
Loss: 32.316618221427696
T= 2000
Loss: 32.30550143999712
T= 2500
Loss: 32.27811453006785
T= 3000
Loss: 32.27609254498203
T= 3500
Loss: 32.27202416236987
T= 4000
Loss: 32.27145532410661
T= 4500
Loss: 32.27071220396665
T= 5000
Loss: 32.2704898613911
T= 5500
Loss: 32.27029923716325
T= 6000
Loss: 32.27020178093319
T= 6500
Loss: 32.270138334495954
T= 7000
Loss: 32.27009371347451
T= 7500
Loss: 32.27006872177711
T= 8000
Loss: 32.27004787287426
T= 8500
Loss: 32.27003703197111
T= 9000
Loss: 32.27002718071076
T= 9500
Loss: 32.27002223155145


# test data read

In [40]:
w = np.load('weight.npy')                                   ## load weight
test_raw_data = np.genfromtxt('test.csv', delimiter=',' ,encoding = 'big5')   ## test.csv
test_data = test_raw_data[:, 2: ]
where_are_NaNs = np.isnan(test_data)
test_data[where_are_NaNs] = 0 

In [41]:
test_x = np.empty(shape = (240, 18 * 9),dtype = float)
for i in range(240):
    test_x[i,:] = test_data[18 * i : 18 * (i+1),:].reshape(1,-1) 
    
test_x = (test_x-np.mean(x,axis=0))/np.std(x,axis=0)
test_x = np.concatenate((np.ones(shape = (test_x.shape[0],1)),test_x),axis = 1).astype(float)
answer = test_x.dot(w)

In [42]:
f = open('submit.csv',"w")
w = csv.writer(f)
title = ['id','value']
w.writerow(title) 
for i in range(240):
    content = ['id_'+str(i),answer[i][0]]
    w.writerow(content) 

In [43]:
answer

array([[  6.57504054],
       [ 18.19419224],
       [ 24.06438673],
       [  7.71980441],
       [ 27.06517062],
       [ 22.20580261],
       [ 23.80578941],
       [ 30.54941033],
       [ 16.81374403],
       [ 59.65252786],
       [ 11.7036484 ],
       [  9.28271862],
       [ 63.23464395],
       [ 53.25518601],
       [ 22.15889153],
       [ 12.22662974],
       [ 32.41412632],
       [ 66.73441927],
       [ -0.50264824],
       [ 17.11141642],
       [ 41.82096437],
       [ 72.16689368],
       [  9.25368473],
       [ 17.89375199],
       [ 14.72188544],
       [ 37.91840279],
       [ 14.66939889],
       [ 67.35995807],
       [  7.22894205],
       [ 55.46144827],
       [ 24.50125225],
       [  8.52804676],
       [  2.53599677],
       [ 18.65167078],
       [ 27.68050823],
       [ 37.24770926],
       [ 43.24300941],
       [ 29.76840577],
       [ 42.13135687],
       [ 35.2458958 ],
       [  7.64122143],
       [ 41.17581933],
       [ 30.5438914 ],
       [ 50